server:
    port: 8080

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/bdqn?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
        username: root
        password: Unioncard9568!
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    redis:
        host: localhost
        port: 6379
mybatis:
    mapper-locations: classpath:/com/zedfeorius/springweb04/mapper/*.xml
    type-aliases-package: com.zedfeorius.springweb04.entity